language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t myreactimage -f Dockerfile.dev .

scripts:
  - docker run -e CI=true myreactimage  npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-691424038304"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"

  